#:import dp kivy.metrics.dp
#:import sp kivy.metrics.sp

<DashboardScreen>:

    BoxLayout:
        orientation: "vertical"
        padding: dp(10)
        spacing: dp(10)
        canvas.before:
            Rectangle:
                source: "assets/image.png"
                pos: self.pos
                size: self.size

        Label:
            text: "My Daily Task"
            font_size: sp(28)
            size_hint_y: None
            height: dp(40)


        ScrollView:

            BoxLayout:
                orientation: "vertical"
                spacing: dp(15)
                size_hint_y: None
                height: self.minimum_height

                Label:
                    text: "Fixed Tasks"
                    bold: True
                    size_hint_y: None
                    height: dp(35)

                BoxLayout:
                    id: fixed_container
                    orientation: "vertical"
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

                Label:
                    text: "Growing Tasks"
                    bold: True
                    size_hint_y: None
                    height: dp(35)

                BoxLayout:
                    id: growing_container
                    orientation: "vertical"
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

            
        BoxLayout:
            size_hint_y: None
            height: dp(46)
            spacing: dp(5)

            Button:
                text: "+ Add Task"
                size_hint_y: None
                height: dp(45)

                background_color: 1, 1, 1, .45
                background_normal: ''
                background_down: ''
                color: 1, 1, 1, 1
                canvas.after:
                    Color:
                        rgb: 1, 1, 1, 0.9
                    Line:
                        width: 1.2
                        rectangle: (self.x, self.y, self.width, self.height)

                on_release:
                    root.add_task()

            Button:
                text: "Progress Details"
                size_hint_y: None
                height: dp(45)

                background_color: 1, 1, 1, .45
                background_normal: ''
                background_down: ''
                color: 1, 1, 1, 1
                canvas.after:
                    Color:
                        rgb: 1, 1, 1, 0.9
                    Line:
                        width: 1.2
                        rectangle: (self.x, self.y, self.width, self.height)

                on_release:
                    root.open_statistics()

           # Button:
            #    text: "Alarm"
            #    size_hint_y: None
            #    height: dp(45)

            #    background_color: 1, 1, 1, .45
            #    background_normal: ''
            #    background_down: ''
            #    color: 1, 1, 1, 1
            #    canvas.after:
            #        Color:
            #            rgb: 1, 1, 1, 0.9
            #        Line:
            #            width: 1.2
            #            rectangle: (self.x, self.y, self.width, self.height)

            #    on_release:
            #        root.open_alarm()