#:import dp kivy.metrics.dp
#:import sp kivy.metrics.sp

<StatisticsScreen>

    BoxLayout:
        orientation: "vertical"
        canvas.before:
            Rectangle:
                source: "assets/image.png"
                pos: self.pos
                size: self.size

        Label:
            text: "Progress Details"
            font_size: sp(25)
            bold: True
            size_hint_y: None
            height: dp(60)

        ScrollView:

            BoxLayout:
                orientation: "vertical"
                padding: dp(20)
                spacing: dp(20)
                size_hint_y: None
                height: self.minimum_height

                BoxLayout:
                    orientation: "vertical"
                    padding: dp(15)
                    spacing: dp(10)
                    size_hint_y: None
                    height: dp(130)

                    color: 1, 1, 1, 1
                    background_normal: ''
                    background_color: 0, 0, 0, 0
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 0.12
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(12),]
                        Color:
                            rgba: 1, 1, 1, 0.25
                        Line:
                            rounded_rectangle: (self.x, self.y, self.width, self.height, dp(12))
                            width: dp(1)


                    BoxLayout:
                        size_hint_y: None
                        height: dp(35)

                        Label:
                            text: "Today's Progress"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: progress
                            text: "0 %"
                            bold: True
                            halign: "right"
                            text_size: self.size

                    ProgressBar:
                        max: 100
                        value: float(progress.text.replace("%","").strip() or "0")

                GridLayout:
                    cols: 1
                    spacing: dp(8)
                    padding: dp(15)
                    size_hint_y: None
                    height: dp(250)

                    color: 1, 1, 1, 1
                    background_normal: ''
                    background_color: 0, 0, 0, 0
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 0.12
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(12),]
                        Color:
                            rgba: 1, 1, 1, 0.25
                        Line:
                            rounded_rectangle: (self.x, self.y, self.width, self.height, dp(12))
                            width: dp(1)


                    BoxLayout:

                        Label:
                            text: "Total Tasks"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: total_tasks
                            text: "0"
                            halign: "right"
                            text_size: self.size

                    BoxLayout:

                        Label:
                            text: "Completed Today"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: completed_today
                            text: "0 / 0"
                            halign: "right"
                            text_size: self.size

                    BoxLayout:

                        Label:
                            text: "Total Completions"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: total_completed
                            text: "0"
                            halign: "right"
                            text_size: self.size

                    BoxLayout:

                        Label:
                            text: "Fixed Tasks"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: fixed_tasks
                            text: "0"
                            halign: "right"
                            text_size: self.size

                    BoxLayout:

                        Label:
                            text: "Growing Tasks"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: growing_tasks
                            text: "0"
                            halign: "right"
                            text_size: self.size

                    BoxLayout:

                        Label:
                            text: "Current Streak"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: current_streak
                            text: "0 Days"
                            halign: "right"
                            text_size: self.size

                    BoxLayout:

                        Label:
                            text: "Best Streak"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: best_streak
                            text: "0 Days"
                            halign: "right"
                            text_size: self.size

                BoxLayout:
                    orientation: "vertical"
                    padding: dp(15)
                    spacing: dp(10)
                    size_hint_y: None
                    height: dp(90)

                    color: 1, 1, 1, 1
                    background_normal: ''
                    background_color: 0, 0, 0, 0
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 0.12
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(12),]
                        Color:
                            rgba: 1, 1, 1, 0.25
                        Line:
                            rounded_rectangle: (self.x, self.y, self.width, self.height, dp(12))
                            width: dp(1)


                    Label:
                        text: "Highest Growing Task"
                        bold: True
                        halign: "left"
                        text_size: self.size

                    BoxLayout:

                        Label:
                            id: highest_task
                            text: "None"
                            halign: "left"
                            text_size: self.size

                        Label:
                            id: highest_target
                            text: "Target : 0"
                            halign: "right"
                            text_size: self.size

                # Extra spacing so the last card isn't too close
                Widget:
                    size_hint_y: None
                    height: dp(10)

        Button:
            text: "Back"
            size_hint: None, None
            width: dp(100)
            height: dp(40)
            pos_hint: {"center_x": 0.5}

            color: 0.8, 0.9, 0.9, 1
            background_normal: ''
            background_color: 0, 0, 0, 0

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 0.08
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(20),]

                Color:
                    rgba: 0, 0.67, 0.7, 0.6
                Line:
                    rounded_rectangle: (self.x, self.y, self.width, self.height, dp(20))
                    width: dp(1.2)

            on_release:
                root.manager.current = "dashboard"