#:import dp kivy.metrics.dp
#:import sp kivy.metrics.sp

<TaskCard>:
    orientation: "vertical"
    spacing: dp(8)
    padding: dp(10), dp(10)
    size_hint_y: None
    height: dp(100)
    color: 1, 1, 1, 1
    background_normal: ''
    background_color: 0, 0, 0, 0
    canvas.before:
        Color:
            rgba: 1, 1, 1, 0.12
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(12),]
        Color:
            rgba: 1, 1, 1, 0.25
        Line:
            rounded_rectangle: (self.x, self.y, self.width, self.height, dp(12))
            width: dp(1)


    BoxLayout:
        orientation: "horizontal"
        padding: dp(10)

        Label:
            text: root.title.title()
            size_hint_x: None
            font_size: sp(20)
            width: self.texture_size[0]

        Widget:

        Label:
            text: "Target : {} - {}".format(root.target, root.unit)
            size_hint_x: None
            width: self.texture_size[0]

        Widget:

        Label:
            text: root.growth
            size_hint_x: None
            width: self.texture_size[0]


    BoxLayout:
        size_hint_y: None
        height: dp(35)
        spacing: dp(5)

        Button:
            text: "Completed" if root.completed else "Done"
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            disabled: root.completed

            canvas.after:
                Color:
                    rgba: 0, 0.67, 0.7, 1
                Line:
                    rounded_rectangle: self.x, self.y, self.width, self.height, dp(25)

            on_release:
                root.show_complete_popup()

        Button:
            text: "Edit"
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            canvas.after:
                Color:
                    rgba: 0, 0.67, 0.7, 1
                Line:
                    rounded_rectangle: self.x, self.y, self.width, self.height, dp(25)
            on_release:
                root.edit_task()

        Button:
            text: "Delete"

            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            canvas.after:
                Color:
                    rgba: 0, 0.67, 0.7, 1
                Line:
                    rounded_rectangle: self.x, self.y, self.width, self.height, dp(25)

            on_release:
                root.show_delete_popup()
    
        Button:
            text: "Timer"
            
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 1
            canvas.after:
                Color:
                    rgba: 0, 0.67, 0.7, 1
                Line:
                    rounded_rectangle: self.x, self.y, self.width, self.height, dp(25)

            on_release:
                root.start_timer()